services:
  db:
    image: mysql:8
    container_name: mysql-mangadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mangadb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: nest-api
    restart: unless-stopped
    ports:
      - "3000:3001"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: devuser
      DATABASE_PASSWORD: devpass
      DATABASE_NAME: mangadb
    

volumes:
  db_data: