name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Raspberry Pi
      run: |
        ssh -o StrictHostKeyChecking=no mdervaux@82.66.21.68 << 'EOF'
          cd /home/mdervaux/api-mangastate
          git pull origin master
          docker-compose down
          docker-compose build 
          docker-compose up -d 
        EOF
